config/routes.rb
Rails.application.routes.draw do
  resources :breeds, only: %i[index show] do
    collection do
      get "search"
    end
  end

  resources :dogs, only: %i[index show] do
    collection do
      get "search"
    end
  end

  get 'about', to: 'pages#show', as: 'about'

  root to: "breeds#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_many :dogs

  validates :name, presence: true, uniqueness: true
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :breed
  
  has_many :dog_owners
  has_many :owners, through: :dog_owners

  validates :name, presence: true, uniqueness: true
  validates :image_url, presence: true
  validates :breed, presence: true
end

app/models/dog_owner.rb
class DogOwner < ApplicationRecord
  belongs_to :dog
  belongs_to :owner
  
  validates :dog_id, presence: true
  validates :owner_id, presence: true
  validates :dog_id, uniqueness: { scope: :owner_id }
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :dog_owners
  has_many :dogs, through: :dog_owners

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  def index
    @breeds = Breed.order(:name).page(params[:page])
  end

  def show
    @breed = Breed.find(params[:id])
  end
  
  def search
    @breeds = Breed.order(:name)

    if params[:keywords].present?
    wildcard_search = "%#{params[:keywords]}%"
    @breeds = @breeds.where("name LIKE ?", wildcard_search)
    end

    if params[:dog_id].present?
      @breeds = @breeds.where(id: params[:dog_id])
    end
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.order(:name).page(params[:page])
  end

  def show
    @dog = Dog.find(params[:id])
    @dogs = Dog.where(name: @dog.name)
  end
    
  def search
    @dogs = Dog.order(:name)

    if params[:keywords].present?
    wildcard_search = "%#{params[:keywords]}%"
    @dogs =  @dogs.where("dogs.name LIKE ?", wildcard_search)
    end
    if params[:breed_id].present?
      @dogs = @dogs.where(breed_id: params[:breed_id])
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/breeds/index.html.erb
<h1>All Breeds</h1>

<%= form_with url: search_breeds_path, method: :get do |form| %>
  <p>Search for a Breed:</p>
  <%= form.text_field :keywords %> 

  <%= label_tag :dog_id, "Filter by Dog name:" %>
  <%= form.collection_select :dog_id, Breed.all.order(:name), :id, :name, prompt: "All dogs" %>

  <%= form.submit "Search" %>
<% end %>

<ul>
  <% @breeds.each do |breed| %>
    <li><%= link_to breed.name, breed %></li>
  <% end %>
</ul>

<%= paginate @breeds %>

app/views/breeds/search.html.erb
<p class="mb-5">Found <%= pluralize(@breeds.count, 'Breed') %> when searching for: <%= params[:keywords] %></p>

<ul>
  <% @breeds.each do |breed| %>
    <li>
      Breed name: <%= link_to breed.name, breed %>, 
        <ul>
          <% breed.dogs.each do |dog| %>
            <li>Dog name: <%= dog.name %></li>
          <% end %>
        </ul>
    </li>
  <% end %>
</ul>

app/views/breeds/show.html.erb
<h1><%= @breed.name %></h1>
<h2>This breed has <%= @breed.dogs.count %> dogs.</h2>

<div>
    <% @breed.dogs.each do |dog| %>
    <div style="margin: 0px">
      <%= link_to "Dog name: #{dog.name}", dog %>

      <% dog.owners.each do |owner| %>
      <div>Owner: <%= owner.name %>, email: <%= owner.email %></div>
      <% end %>

      <%= link_to image_tag(dog.image_url, alt: "Image of #{dog.name}", :size => "400x400"), dog %>
    </div>
    <% end %>
</div>

app/views/dogs/index.html.erb
<h1>All Dogs</h1>

<%= form_with url: search_dogs_path, method: :get do |form| %>
  <p>Search for dog name:</p>
  <%= form.text_field :keywords %> 

  <%= label_tag :breed_id, "Filter by breed:" %>
  <%= form.collection_select :breed_id, Breed.all.order(:name), :id, :name, prompt: "All breeds" %>

  <%= form.submit "Search" %>
<% end %>

<ul>
    <% @dogs.each do |dog| %>
    <li><%= link_to dog.name, dog %></li>
    <% end %>
</ul>

<%= paginate @dogs %>

app/views/dogs/search.html.erb
<p class="mb-5">Found <%= pluralize(@dogs.count, 'Dog') %> name when searching for: <%= params[:keywords] %></p>

<ul>
  <% @dogs.each do |dog| %>
    <li>Dog name:<%= link_to dog.name, dog %>, Breed name:<%= dog.breed.name %></li>
  <% end %>
</ul>

app/views/dogs/show.html.erb
<h1>Images of All Dogs Named "<%= @dog.name %>"</h1>

<h2>Breed:<%= link_to @dog.breed.name, @dog.breed %></h2>

<div>
    <% @dogs.each do |dog| %>
        <% dog.owners.each do |owner| %>
        <p style="margin: 0px">Owner Name: <%= owner.name %>, Email: <%= owner.email %> </p>
        <% end %>

        <%= link_to image_tag(dog.image_url, alt: "Image of #{dog.name}", :size => "400x400"), dog %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Dog App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <h1>Dogs App</h1>
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Dogs", dogs_path %></li>
          <li><%= link_to "About", about_path %></li>
        </ul>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/pages/show.html.erb
<h1>About This Application</h1>

<h2>Data Sources</h2>
<ul>
    <li>Dog API: This API provides images of dogs.</li>
    <li>Faker: This Faker generates fake dog and breed names.</li>
    <li>CSV File: This CSV file provides owner information, including names and email addresses.</li>
</ul>

<h2>Data Structure</h2>
<ul>
    <li>Dog model: This table includes name, image_url and breed_id columns.</li>
    <li>Breed model: This table include dog breed names.</li>
    <li>Owner model: This table includes name and email.</li>
    <li>DogOwner model: This join table establishes a many-to-many relationship between Dog and Owner, 
        with each dog having up to two owners and each owner having up to two dogs.</li>
</ul>

<h2>Plan to integrate the different Datasets</h2>
<ul>
    <li>Use Faker gem to creat dog breeds and save them in the Breed model.</li>
    <li>Use Dog API to save image_url and use Faker gem to create dog name in the Dog model.</li>
    <li>Use a CSV file to populate owner information in the Owner model.</li>
    <li>When creating a Dog object, include an image URL from the Dog API and assign a `breed_id` that references a random breed from the Breed table.</li>
    <li>Establish relationships:
        <ul>
            <li>Each breed can have multiple dogs associated with it (one-to-many).</li>
            <li>Each dog can have up to two owners, and each owner can have up to two dogs (many-to-many).</li>
        </ul>
    </li>
</ul>

<h2>ERD</h2>
<%= image_tag 'dog_app_ERD.png', alt: "Image of ERD" %>